# Generated by Django 5.1.5 on 2025-04-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="pokemon_id",
            field=models.CharField(default="default-id", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
