# Generated by Django 5.1.5 on 2025-04-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_listing_pokemon_id_listing_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="pokemon_id",
            field=models.CharField(default="default-id", max_length=50),
        ),
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name="RequestTrade",
        ),
    ]
