# Generated by Django 5.2 on 2025-04-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_requesttrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
    ]
