# Generated by Django 5.2 on 2025-04-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='card_name',
            field=models.CharField(default='n/a', max_length=100),
        ),
    ]
