# Generated by Django 5.2 on 2025-04-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_trade_card_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='card_id',
            new_name='sender_card',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='card_name',
        ),
        migrations.AddField(
            model_name='trade',
            name='recipient_card',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('awaiting_response', 'Awaiting Response')], default='pending', max_length=20),
        ),
    ]
