# Generated by Django 5.2 on 2025-04-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_rename_card_id_trade_sender_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('countered', 'Countered'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
