# Generated by Django 5.1.5 on 2025-04-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneratedCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("primary_type", models.CharField(max_length=50)),
                (
                    "secondary_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("rarity", models.CharField(max_length=50)),
                ("art_style", models.CharField(max_length=50)),
                ("hp", models.IntegerField()),
                ("attack", models.IntegerField()),
                ("defense", models.IntegerField()),
                ("image_url", models.URLField(blank=True, null=True)),
                (
                    "image_local_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
